/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class LoginForm extends javax.swing.JFrame {

    public Connection connection;

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUp_selection = new javax.swing.ButtonGroup();
        signIn_selection = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        phone_txt = new javax.swing.JTextField();
        password_txt = new javax.swing.JPasswordField();
        login_btn = new javax.swing.JButton();
        personal_user_signin = new javax.swing.JRadioButton();
        biller_signin = new javax.swing.JRadioButton();
        error_txt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        personal_user = new javax.swing.JRadioButton();
        biller = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phone_txt.setBackground(new java.awt.Color(255, 199, 196));
        phone_txt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        phone_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phone_txt.setBorder(null);
        phone_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_txtActionPerformed(evt);
            }
        });
        jPanel2.add(phone_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 175, 260, 30));

        password_txt.setBackground(new java.awt.Color(255, 199, 196));
        password_txt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        password_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password_txt.setBorder(null);
        password_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_txtActionPerformed(evt);
            }
        });
        jPanel2.add(password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 260, 30));

        login_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_SignIn.png"))); // NOI18N
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        jPanel2.add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 116, 30));

        personal_user_signin.setBackground(new java.awt.Color(232, 2, 59));
        signIn_selection.add(personal_user_signin);
        personal_user_signin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        personal_user_signin.setForeground(new java.awt.Color(255, 255, 255));
        personal_user_signin.setText("Personal User");
        jPanel2.add(personal_user_signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        biller_signin.setBackground(new java.awt.Color(232, 2, 59));
        signIn_selection.add(biller_signin);
        biller_signin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        biller_signin.setForeground(new java.awt.Color(255, 255, 255));
        biller_signin.setText("Biller");
        jPanel2.add(biller_signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        error_txt.setBackground(new java.awt.Color(255, 255, 255));
        error_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        error_txt.setForeground(new java.awt.Color(255, 255, 255));
        error_txt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error_txt.setEnabled(false);
        jPanel2.add(error_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 385, 192, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Forget Password?");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login_bg_personal.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 410));

        personal_user.setBackground(new java.awt.Color(255, 255, 255));
        signUp_selection.add(personal_user);
        personal_user.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        personal_user.setForeground(new java.awt.Color(232, 2, 59));
        personal_user.setText("Personal User");
        jPanel1.add(personal_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, -1, -1));

        biller.setBackground(new java.awt.Color(255, 255, 255));
        signUp_selection.add(biller);
        biller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        biller.setForeground(new java.awt.Color(232, 2, 59));
        biller.setText("Biller");
        jPanel1.add(biller, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_Agent.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_Admin.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_SignUp.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 330, 40));

        jLabel2.setForeground(new java.awt.Color(232, 2, 59));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background_Sign.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 584));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phone_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_txtActionPerformed

    public void textVisibilty() {
        error_txt.setVisible(false);
    }

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        // TODO add your handling code here:
        String phoneNo = phone_txt.getText();
        String password = String.valueOf(password_txt.getPassword());

        try {

            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=eWallet;selectMethod=cursor", "sa", "123456");

            System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());

            if (personal_user_signin.isSelected()) {
                Statement statement = connection.createStatement();
                ResultSet resultSet = statement
                        .executeQuery("SELECT Password, Name FROM INFORMATION INNER JOIN PERSONAL ON INFORMATION.Contact = PERSONAL.Contact where INFORMATION.contact = " + phoneNo +"and PersonalID Like '3%'");

                int take = 1;
                while (resultSet.next()) {
                    take = 2;
                    String resultPass = resultSet.getString("Password");
                    String name = resultSet.getString("Name");
                    if (password.equals(resultPass)) {

                        this.setVisible(false);
                        new HomepagePersonal(name,phoneNo).setVisible(true);
                        break;
                    } else {
                        error_txt.setText("Incorrect Password");
                    }

                }
                if (take == 1) {
                    error_txt.setText("Incorrect phone or password");
                }
            } else if (biller_signin.isSelected()) {
                Statement statement = connection.createStatement();
                ResultSet resultSet = statement
                        .executeQuery("SELECT Password, CompanyName FROM INFORMATION INNER JOIN BILLER ON INFORMATION.Contact = BILLER.Contact where INFORMATION.contact = " + phoneNo +"and BillerID Like '4%'");

                int take = 1;
                while (resultSet.next()) {
                    take = 2;
                    String resultPass = resultSet.getString("Password");
                    String CompanyName = resultSet.getString("CompanyName");

                    if (password.equals(resultPass)) {

                        this.setVisible(false);
                        new HomepageBiller(CompanyName, phoneNo).setVisible(true);
                        break;
                    } else {
                        error_txt.setText("Incorrect Password");
                    }

                }
                if (take == 1) {
                    error_txt.setText("Incorrect phone or password");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please select account type.");
            }

//            while (resultSet.next()) {
//                
//                System.out.println("Customer NAME:" + 
//                        resultSet.getString("Password"));
//                
//            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_login_btnActionPerformed

    private void password_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_txtActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        LoginFormAdmin lf_Admin = new LoginFormAdmin();
        lf_Admin.setVisible(true);
        lf_Admin.pack();
        lf_Admin.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        LoginFormAgent lf_Agent = new LoginFormAgent();
        lf_Agent.setVisible(true);
        lf_Agent.pack();
        lf_Agent.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        //int choice = JOptionPane.showConfirmDialog(null,"Do you want to sign up as a personal account?","Logout",JOptionPane.YES_NO_OPTION);
        if (personal_user.isSelected()) {
            RegistrationFormUserAndAgent lf_personal = new RegistrationFormUserAndAgent();
            lf_personal.setVisible(true);
            lf_personal.pack();
            lf_personal.setLocationRelativeTo(null);
            this.dispose();
        } else if (biller.isSelected()) {
            RegistrationFormBiller lf_agent = new RegistrationFormBiller();
            lf_agent.setVisible(true);
            lf_agent.pack();
            lf_agent.setLocationRelativeTo(null);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Please select account type.");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        ForgetPassword forgetPassword = new ForgetPassword();
        forgetPassword.setVisible(true);
        forgetPassword.pack();
        forgetPassword.setLocationRelativeTo(null);
        this.dispose();
        
        
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton biller;
    private javax.swing.JRadioButton biller_signin;
    private javax.swing.JLabel error_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login_btn;
    private javax.swing.JPasswordField password_txt;
    private javax.swing.JRadioButton personal_user;
    private javax.swing.JRadioButton personal_user_signin;
    private javax.swing.JTextField phone_txt;
    private javax.swing.ButtonGroup signIn_selection;
    private javax.swing.ButtonGroup signUp_selection;
    // End of variables declaration//GEN-END:variables
}
