/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class RegistrationFormBiller extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationFormUserAndAgent
     */
    public RegistrationFormBiller() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        biller_mobile_no = new javax.swing.JTextField();
        biller_name = new javax.swing.JTextField();
        biller_trade_license_no = new javax.swing.JTextField();
        biller_website = new javax.swing.JTextField();
        biller_address = new javax.swing.JTextField();
        biller_district = new javax.swing.JTextField();
        biller_logo = new javax.swing.JTextField();
        biller_answer = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        biller_NID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        biller_security_question = new javax.swing.JComboBox<>();
        biller_confirm_password = new javax.swing.JPasswordField();
        biller_password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        biller_branch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Biller Registartion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_backPress.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Mobile No:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Biller Name:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 145, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Branch: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Trade Leicense No:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Password:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Confirm Password:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Address:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("District:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Security Que:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Answer: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Logo:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, -1));

        biller_mobile_no.setBackground(new java.awt.Color(240, 240, 240));
        biller_mobile_no.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        biller_mobile_no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        biller_mobile_no.setBorder(null);
        biller_mobile_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biller_mobile_noActionPerformed(evt);
            }
        });
        jPanel1.add(biller_mobile_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 202, 220, 30));

        biller_name.setBackground(new java.awt.Color(240, 240, 240));
        biller_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        biller_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        biller_name.setBorder(null);
        biller_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biller_nameActionPerformed(evt);
            }
        });
        jPanel1.add(biller_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 148, 220, 30));

        biller_trade_license_no.setBackground(new java.awt.Color(240, 240, 240));
        biller_trade_license_no.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        biller_trade_license_no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        biller_trade_license_no.setBorder(null);
        biller_trade_license_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biller_trade_license_noActionPerformed(evt);
            }
        });
        jPanel1.add(biller_trade_license_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 258, 220, 30));

        biller_website.setBackground(new java.awt.Color(240, 240, 240));
        biller_website.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        biller_website.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        biller_website.setBorder(null);
        biller_website.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biller_websiteActionPerformed(evt);
            }
        });
        jPanel1.add(biller_website, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 312, 220, 30));

        biller_address.setBackground(new java.awt.Color(240, 240, 240));
        biller_address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        biller_address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        biller_address.setBorder(null);
        biller_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biller_addressActionPerformed(evt);
            }
        });
        jPanel1.add(biller_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 202, 220, 30));

        biller_district.setBackground(new java.awt.Color(240, 240, 240));
        biller_district.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        biller_district.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        biller_district.setBorder(null);
        biller_district.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biller_districtActionPerformed(evt);
            }
        });
        jPanel1.add(biller_district, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 257, 220, 30));

        biller_logo.setBackground(new java.awt.Color(240, 240, 240));
        biller_logo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        biller_logo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        biller_logo.setBorder(null);
        biller_logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biller_logoActionPerformed(evt);
            }
        });
        jPanel1.add(biller_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 423, 220, 30));

        biller_answer.setBackground(new java.awt.Color(240, 240, 240));
        biller_answer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        biller_answer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        biller_answer.setBorder(null);
        biller_answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biller_answerActionPerformed(evt);
            }
        });
        jPanel1.add(biller_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 367, 220, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("NID:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, -1, -1));

        biller_NID.setBackground(new java.awt.Color(240, 240, 240));
        biller_NID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        biller_NID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        biller_NID.setBorder(null);
        biller_NID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biller_NIDActionPerformed(evt);
            }
        });
        jPanel1.add(biller_NID, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 148, 220, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_ConfirmRegistration.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 320, 40));

        biller_security_question.setBackground(new java.awt.Color(240, 240, 240));
        biller_security_question.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your favourite appetizer?", "What is your favourite dessert?", "What is your favourite drink?" }));
        jPanel1.add(biller_security_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 313, 220, 30));

        biller_confirm_password.setBackground(new java.awt.Color(240, 240, 240));
        biller_confirm_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        biller_confirm_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        biller_confirm_password.setBorder(null);
        jPanel1.add(biller_confirm_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 423, 220, 30));

        biller_password.setBackground(new java.awt.Color(240, 240, 240));
        biller_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        biller_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        biller_password.setBorder(null);
        biller_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biller_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(biller_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 368, 220, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/header.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        biller_branch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg_resistration_new.png"))); // NOI18N
        jPanel1.add(biller_branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
            LoginForm lf_personal = new LoginForm();
            lf_personal.setVisible(true);
            lf_personal.pack();
            lf_personal.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void biller_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biller_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biller_passwordActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=eWallet;selectMethod=cursor", "sa", "123456");
            
            String query2 = "Insert into PHOTOGRAPH(PhotoPath)values (?)";
            PreparedStatement st2 = connection.prepareStatement(query2);
            st2.setString(1, biller_logo.getText());
            st2.executeUpdate();
            
            
            
            String query1 = "Insert into INFORMATION (Contact, Password, NationalID, Address, District, SecurityQue,SecurityAns, PhotoPath, AccOpening  )values (?,?,?,?,?,?,?,?,getDate())";
            PreparedStatement st1 = connection.prepareStatement(query1);
            st1.setString(1,biller_mobile_no.getText());
            st1.setString(2,String.valueOf(biller_password.getPassword()));
            st1.setString(3,biller_NID.getText());
            st1.setString(4,biller_address.getText());
            st1.setString(5,biller_district.getText());
            st1.setString(6,biller_security_question.getSelectedItem().toString());
            st1.setString(7,biller_answer.getText());
            st1.setString(8,biller_logo.getText());
            //st1.setString(9, "2021-2-15");
            st1.executeUpdate();
            
            
            String query = "Insert into BILLER (Contact, CompanyName, Branch, TradeLicense)values (?,?,?,?)";
            PreparedStatement st = connection.prepareStatement(query);
            st.setString(1, biller_mobile_no.getText() );
            st.setString(2, biller_name.getText());
            st.setString(3, biller_website.getText());
            st.setString(4, biller_trade_license_no.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Inserted!");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
//        
//        try {
//            
//            
//            String name = biller_mobile_no.getText();
//            String mobile = biller_mobile_no.getText();
//            
//            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
//            Connection connection = DriverManager.getConnection(
//                    "jdbc:sqlserver://localhost:1433;databaseName=eWallet;selectMethod=cursor", "sa", "123456");
//
//            System.out.println("DATABASE NAME IS:" + connection.getMetaData().getDatabaseProductName());
//
//            Statement statement = connection.createStatement();
////            ResultSet resultSet = statement
////                   .executeQuery("SELECT Contact, Password  FROM INFORMATION where contact = "+mobile);
//            
//      
//            PreparedStatement st;
//                    ResultSet rs;
//                
//                String Query = "INSERT INTO `BILLER`(`CompanyName`) VALUES (?) ";
//                try {
//                   st = connection.prepareStatement(Query);
//                   st.setString(1, name);
//                   
////            
//            
//            
////            int take = 1; 
////            while(resultSet.next())
////            {
////                take = 2;
////                String resultPass = resultSet.getString("Password");
////                
////                if(password.equals(resultPass)){
////                    this.setVisible(false);
////                    new HomepagePersonal().setVisible(true);
////                    break;
////                }else{
////                    error_txt.setText("Incorrect Password");
////                }
////                
////            }
////            if(take==1){
////                error_txt.setText("Incorrect phone or password");
////            }
//            
////            while (resultSet.next()) {
////                
////                System.out.println("Customer NAME:" + 
////                        resultSet.getString("Password"));
////                
////            }
//                 
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//        
//        
//        } catch (Exception e) {
//            e.printStackTrace();
//        }  
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void biller_mobile_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biller_mobile_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biller_mobile_noActionPerformed

    private void biller_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biller_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biller_nameActionPerformed

    private void biller_trade_license_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biller_trade_license_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biller_trade_license_noActionPerformed

    private void biller_websiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biller_websiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biller_websiteActionPerformed

    private void biller_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biller_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biller_addressActionPerformed

    private void biller_districtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biller_districtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biller_districtActionPerformed

    private void biller_logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biller_logoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biller_logoActionPerformed

    private void biller_answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biller_answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biller_answerActionPerformed

    private void biller_NIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biller_NIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biller_NIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationFormBiller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationFormBiller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationFormBiller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationFormBiller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationFormBiller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biller_NID;
    private javax.swing.JTextField biller_address;
    private javax.swing.JTextField biller_answer;
    private javax.swing.JLabel biller_branch;
    private javax.swing.JPasswordField biller_confirm_password;
    private javax.swing.JTextField biller_district;
    private javax.swing.JTextField biller_logo;
    private javax.swing.JTextField biller_mobile_no;
    private javax.swing.JTextField biller_name;
    private javax.swing.JPasswordField biller_password;
    private javax.swing.JComboBox<String> biller_security_question;
    private javax.swing.JTextField biller_trade_license_no;
    private javax.swing.JTextField biller_website;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
