/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class RegistrationFormUserAndAgent extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationFormUserAndAgent
     */
    public RegistrationFormUserAndAgent() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acc_type = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        personal_security_question = new javax.swing.JComboBox<>();
        radio_agent = new javax.swing.JRadioButton();
        radio_personal = new javax.swing.JRadioButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        personal_name = new javax.swing.JTextField();
        personal_mobile_no = new javax.swing.JTextField();
        personal_NID = new javax.swing.JTextField();
        personal_DOB = new javax.swing.JTextField();
        personal_password = new javax.swing.JPasswordField();
        personal_confirm_password = new javax.swing.JPasswordField();
        personal_address = new javax.swing.JTextField();
        personal_district = new javax.swing.JTextField();
        personal_answer = new javax.swing.JTextField();
        personal_photo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Personal / Agent Registartion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_backPress.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Mobile No:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Name:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 145, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Date of Birth: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("NID No:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Password:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Confirm Password:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Address:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("District:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 205, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Security Que:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 255, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Answer: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Account Type:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Photo:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 365, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btn_ConfirmRegistration.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 320, 40));

        personal_security_question.setBackground(new java.awt.Color(240, 240, 240));
        personal_security_question.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your favourite appetizer?", "What is your favourite dessert?", "What is your favourite drink?" }));
        personal_security_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal_security_questionActionPerformed(evt);
            }
        });
        jPanel1.add(personal_security_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 258, 220, 30));

        radio_agent.setBackground(new java.awt.Color(255, 255, 255));
        acc_type.add(radio_agent);
        radio_agent.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        radio_agent.setText("Agent");
        jPanel1.add(radio_agent, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 420, -1, -1));

        radio_personal.setBackground(new java.awt.Color(255, 255, 255));
        acc_type.add(radio_personal);
        radio_personal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        radio_personal.setText("Personal");
        radio_personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_personalActionPerformed(evt);
            }
        });
        jPanel1.add(radio_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(240, 240, 240));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPasswordField1.setBorder(null);
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 425, 220, -1));

        jPasswordField2.setBackground(new java.awt.Color(240, 240, 240));
        jPasswordField2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPasswordField2.setBorder(null);
        jPanel1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 220, -1));

        personal_name.setBackground(new java.awt.Color(240, 240, 240));
        personal_name.setBorder(null);
        personal_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal_nameActionPerformed(evt);
            }
        });
        jPanel1.add(personal_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 148, 220, 30));

        personal_mobile_no.setBackground(new java.awt.Color(240, 240, 240));
        personal_mobile_no.setBorder(null);
        personal_mobile_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal_mobile_noActionPerformed(evt);
            }
        });
        jPanel1.add(personal_mobile_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 202, 220, 30));

        personal_NID.setBackground(new java.awt.Color(240, 240, 240));
        personal_NID.setBorder(null);
        personal_NID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal_NIDActionPerformed(evt);
            }
        });
        jPanel1.add(personal_NID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 258, 220, 30));

        personal_DOB.setBackground(new java.awt.Color(240, 240, 240));
        personal_DOB.setBorder(null);
        personal_DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal_DOBActionPerformed(evt);
            }
        });
        jPanel1.add(personal_DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 312, 220, 30));

        personal_password.setBackground(new java.awt.Color(240, 240, 240));
        personal_password.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        personal_password.setBorder(null);
        personal_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(personal_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 220, -1));

        personal_confirm_password.setBackground(new java.awt.Color(240, 240, 240));
        personal_confirm_password.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        personal_confirm_password.setBorder(null);
        jPanel1.add(personal_confirm_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 425, 220, -1));

        personal_address.setBackground(new java.awt.Color(240, 240, 240));
        personal_address.setBorder(null);
        personal_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal_addressActionPerformed(evt);
            }
        });
        jPanel1.add(personal_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 148, 220, 30));

        personal_district.setBackground(new java.awt.Color(240, 240, 240));
        personal_district.setBorder(null);
        personal_district.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal_districtActionPerformed(evt);
            }
        });
        jPanel1.add(personal_district, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 202, 220, 30));

        personal_answer.setBackground(new java.awt.Color(240, 240, 240));
        personal_answer.setBorder(null);
        personal_answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal_answerActionPerformed(evt);
            }
        });
        jPanel1.add(personal_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 312, 220, 30));

        personal_photo.setBackground(new java.awt.Color(240, 240, 240));
        personal_photo.setBorder(null);
        personal_photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal_photoActionPerformed(evt);
            }
        });
        jPanel1.add(personal_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 368, 220, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/header.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg_resistration.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio_personalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_personalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_personalActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
            LoginForm lf_agent = new LoginForm();
            lf_agent.setVisible(true);
            lf_agent.pack();
            lf_agent.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void personal_security_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal_security_questionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personal_security_questionActionPerformed

    private void personal_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personal_nameActionPerformed

    private void personal_mobile_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal_mobile_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personal_mobile_noActionPerformed

    private void personal_NIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal_NIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personal_NIDActionPerformed

    private void personal_DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal_DOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personal_DOBActionPerformed

    private void personal_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personal_passwordActionPerformed

    private void personal_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personal_addressActionPerformed

    private void personal_districtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal_districtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personal_districtActionPerformed

    private void personal_answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal_answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personal_answerActionPerformed

    private void personal_photoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal_photoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personal_photoActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
         String pass = String.valueOf(personal_password.getPassword());
            System.out.println(pass);
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=eWallet;selectMethod=cursor", "sa", "123456");
            
            
            
            
            String query2 = "Insert into PHOTOGRAPH(PhotoPath)values (?)";
            PreparedStatement st2 = connection.prepareStatement(query2);
            st2.setString(1, personal_photo.getText());
            st2.executeUpdate();
            
            
            
            String query1 = "Insert into INFORMATION (Contact, Password, NationalID, Address, District, SecurityQue,SecurityAns, PhotoPath, AccOpening)values (?,?,?,?,?,?,?,?,?)";
            PreparedStatement st1 = connection.prepareStatement(query1);
            st1.setString(1,personal_mobile_no.getText());
            st1.setString(2,String.valueOf(personal_password.getPassword()));
           
            //st1.setString(2,"qwer12345");
            st1.setString(3,personal_NID.getText());
            st1.setString(4,personal_address.getText());
            st1.setString(5,personal_district.getText());
            st1.setString(6,personal_security_question.getSelectedItem().toString());
            st1.setString(7,personal_answer.getText());
            st1.setString(8,personal_photo.getText());
            st1.setString(9, "2021-2-15");
            st1.executeUpdate();
            
            if(radio_personal.isSelected() )
            {
                System.out.println("personal clicked");
            String query = "Insert into PERSONAL (Contact, Name, DOB)values (?,?,?)";
            PreparedStatement st = connection.prepareStatement(query);
            st.setString(1, personal_mobile_no.getText() );
            st.setString(2, personal_name.getText());
            st.setString(3, personal_DOB.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Inserted!");
            }
            else if(radio_agent.isSelected())
            {
            String query = "Insert into AGENT (Contact, Name, DOB)values (?,?,?)";
            PreparedStatement st = connection.prepareStatement(query);
            st.setString(1, personal_mobile_no.getText() );
            st.setString(2, personal_name.getText());
            st.setString(3, personal_DOB.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Inserted!");
            }else{
                JOptionPane.showMessageDialog(null, "Incorrect info!");
            }
           
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationFormUserAndAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationFormUserAndAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationFormUserAndAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationFormUserAndAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationFormUserAndAgent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup acc_type;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField personal_DOB;
    private javax.swing.JTextField personal_NID;
    private javax.swing.JTextField personal_address;
    private javax.swing.JTextField personal_answer;
    private javax.swing.JPasswordField personal_confirm_password;
    private javax.swing.JTextField personal_district;
    private javax.swing.JTextField personal_mobile_no;
    private javax.swing.JTextField personal_name;
    private javax.swing.JPasswordField personal_password;
    private javax.swing.JTextField personal_photo;
    private javax.swing.JComboBox<String> personal_security_question;
    private javax.swing.JRadioButton radio_agent;
    private javax.swing.JRadioButton radio_personal;
    // End of variables declaration//GEN-END:variables
}
